# en_GB.pl - Generate en_GB messages from en_US
# Copyright (c) 2000, 2003 Kriang Lerdsuwanakij
# email:	lerdsuwa@users.sourceforge.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


print "# Automatically generated by en_GB.pl\n";

$translate = 0;
while (<STDIN>) {
	$line = $_;
	$done = "";
	if ($line =~ /^\s*msgid/) {
		$translate = 0;
	}
	elsif ($line =~ /^\s*msgstr/) {
		$translate = 1;
	}

	if ($translate == 1 && $line !~ /^\#/) {

							# English words
		s/(c|C)olor/$1olour/g;
		s/(p|P)rogram/$1rogramme/g;

		s/(i|I)nitializ/$1nitialis/g;
		s/(o|O)ptimiz/$1ptimis/g;
		s/(r|R)ecogniz/$1ecognis/g;
		s/(s|S)pecializ/$1pecialis/g;

							# Date/time formats
		s/\%b \%d, \%Y/\%d \%b \%Y/g;
		s/\%b \%d/\%d \%b/g;
		s/\%b \%e, \%Y/\%e \%b \%Y/g;
		s/\%b \%e/\%e \%b/g;

		$done = $_;
	}
	else {
		$done = $_;
	}
	print $done;
}
