#! /usr/bin/env perl
# miscout
# Copyright (c) 2000 Kriang Lerdsuwanakij
# email:	lerdsuwa@users.sourceforge.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

$prog_name = "miscout";
$prog_ver = "2.0.0";

if (@ARGV != 2) {
	print "$prog_name $prog_ver\n";
	print "usage $prog_name size FILE\n";
	exit 0;
}

if ($ARGV[0] eq "size") {
	if (-e $ARGV[1]) {
		($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
			$atime,$mtime,$ctime,$blksize,$blocks) = stat $ARGV[1];
		if ($size < 102400) {
			print "$size\n";
		}
		else {
			print int(($size+512)/1024);
			print "k\n";
		}
	}
	else {
		print "$prog_name: $ARGV[1] not found\n";
	}
}
else {
	print "$prog_name: unknown output\n";
}
